### ISSUE TITLE
Verify fields passed into MyModule.new/1

### ISSUE THREAD

**Issue by whatyouhide** [bitwalker/exprotobuf#109]
I might be wrong, but from my experiments using proto3 and exprotobuf, it seems like if I have a definition:

```proto
message Foo {
  string bar = 1;
}
```

and I compile it with exprotobuf, this happens:

```elixir
Foo.new(baz: "typo!")
#=> %Foo{bar: nil}
```

If I'm not doing anything wrong myself, shouldn't we check that the fields passed into `Foo.new/1` actually match all the fields defined by the schema (that is, `struct!/2` behaviour and not `struct/2` behaviour)?

\cc @bitwalker

**Comment by relistan** [comment]
This is critically needed, IMO

**Comment by whatyouhide** [comment]
@bitwalker ping?

**Comment by whatyouhide** [comment]
Seems like activity on the repo is very low, and we've switched to something else so this is not personally an issue for us anymore. @bitwalker I still believe that, provided I'm not missing something, this is a bug and the described behavior would be the correct one, but I need to keep my issues tidy so I'll close this 😄  Please feel free to reopen in the future!
