### ISSUE TITLE
Can't parse `syntax` field (see thread for more details)

### ISSUE THREAD

**Issue by mbilokonsky** [bitwalker/exprotobuf#18]
I'm not sure where this bug lives, exactly, but it looks like maybe :gpb is throwing up when attempting to parse this file?

https://developers.google.com/transit/gtfs-realtime/gtfs-realtime-proto

I pulled down that file, stuck it into /priv, and wrote the following module definition:

```defmodule GTFS do
  use Protobuf, from: "priv/gtfs-realtime.proto"
end```

But when I try to compile my code, I get this error: 

```
== Compilation error on file lib/tap/protobuf/GTFS.ex ==
** (ArgumentError) argument error
    :erlang.byte_size({25, :gpb_parse, ['syntax error before: ', 'syntax']})
    (elixir) lib/exception.ex:106: Exception.format_banner/3
    (elixir) lib/exception.ex:141: Exception.format/3
    (elixir) lib/kernel/parallel_compiler.ex:216: Kernel.ParallelCompiler.print_failure/2
    (elixir) lib/kernel/parallel_compiler.ex:189: Kernel.ParallelCompiler.handle_failure/5
    (elixir) lib/kernel/parallel_compiler.ex:182: Kernel.ParallelCompiler.wait_for_messages/8
    (elixir) lib/kernel/parallel_compiler.ex:55: Kernel.ParallelCompiler.spawn_compilers/3
    (mix) lib/mix/compilers/elixir.ex:112: Mix.Compilers.Elixir.compile_manifest/5
```

Frustratingly, when I call protoc on that file from the command line to generate a .desc file it works just fine - so I know it's not a malformed input.proto file.

Any idea what could be causing this?

**Comment by Tuxified** [comment]
Hi,

I saw your question on slack, seems like the line `syntax = "proto2";` causes the problem. Removing that line helped me to compile the module. Not sure what the effect is of removing that line (will it be able to process / decode data), but it gives you a hint.

Hope that helps.

**Comment by mbilokonsky** [comment]
thanks! Can I ask how you were able to identify that line as the culprit?

**Comment by mbilokonsky** [comment]
was gonna try to write some failing tests but the whole thing just crashes and exists with that `syntax` field even in the module def so I'm gonna say that's a gpb issue...?

**Comment by koudelka** [comment]
The syntax declaration isn't part of the [proto2 spec](https://developers.google.com/protocol-buffers/docs/proto), as far as I can tell. I think it might have been something they added to the [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3). 

I think it's an upstream issue, since gpb is responsible for parsing.

**Comment by bitwalker** [comment]
@mbilokonsky @koudelka  Yeah looks like it was added [here](https://github.com/google/protobuf/blob/master/CHANGES.txt#L220). I'm not sure what the status of proto3 support is in gpb at the moment, but any issues related to the parser would have to get fixed upstream before we can support it in exprotobuf :(

**Comment by tommyogp** [comment]
:+1:  having this issue as well, even after I removed `syntax`, some portions of our codes contain elements that can't be parsed, e.g. `extend`. Hope this can be fixed soon. I'm gonna do some investigation as well.

**Comment by bitwalker** [comment]
@tommyogp Definitely hit up the `gpb` repo and open an issue requesting proto3 support, until it's supported upstream, there isn't much I can do on this :(

**Comment by Inkp** [comment]
Looks like proto3 is now supported by gpb. Can we expect update of this repo as well?

**Comment by bitwalker** [comment]
The latest release contains the latest release of gpb. I'll close this for now. Please open up specific issues as needed if things are still missing.

**Comment by tony612** [comment]
@bitwalker How about publishing a new version? I need gpb 3.24 :)

**Comment by bitwalker** [comment]
@tony612 done :)

**Comment by tony612** [comment]
@bitwalker 👍  Thanks! ❤️
