### ISSUE TITLE
protodefs are not recompiled if changed

### ISSUE THREAD

**Issue by vans163** [bitwalker/exprotobuf#24]
nevermind this seems an issue on my end. Looking into further.

Issue was I did not realize that the lib was not recompiling the defs when I changed the file.  There should be a check I think perhaps you can include the file + a checksum.

Everytime use Protobuf executes, check the protofiles MD5, if it does not match the md5 you wrote, recompile the defs?

**Comment by rafal-radziszewski** [comment]
As far as I know:

Mix recompiles files that changed and are in paths specified in elixirs_paths. If a file changes, it's recompiled. In case of proto changes, you would have to tell mix to recompile importing module any time one of proto files changes. I do not think that's easy to do. You always can recompile your project when you change proto definitions.

**Comment by dokie** [comment]
Try something like this
``` elixir
defmodule Protobuf.Messages do
  @moduledoc """
  This is where the Protocol Buffers Messages get defined and brought into our App.
  """
  @external_resource Path.expand("../protobuf/messages.proto", __DIR__)

  use Protobuf, from: Path.expand("../protobuf/messages.proto", __DIR__)
end
```

**Comment by fireyang** [comment]
@dokie external_resource is not work ,why?

**Comment by bitwalker** [comment]
Should be fixed in master now
