### ISSUE TITLE
Cannot build as a dependency in Elixir 1.1

### ISSUE THREAD

**Issue by saratchandra92** [bitwalker/exprotobuf#26]
The error I am getting when trying to compile the project is

```
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

==> gpb (compile)
Compiling src/gpb_scan.xrl failed:
ERROR: compile failed while processing /home/sarat/projects/protobuf_elixir/deps/gpb: rebar_abort
** (Mix) Could not compile dependency :gpb, "/home/sarat/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile gpb", update it with "mix deps.update gpb" or clean it with "mix deps.clean gpb"
```

I am using Elixir 1.1 and Erlang 18(erts-7.1)

Here is my mix.exs file 

```elixir
defmodule ProtobufElixir.Mixfile do
  use Mix.Project

  def project do
    [app: :protobuf_elixir,
     version: "0.0.1",
     elixir: "~> 1.1",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [{:exprotobuf, "~>0.11"}]
  end
end

```

**Comment by bitwalker** [comment]
`exprotobuf` supports Elixir 1.1/Erlang 18+ (which I verified locally with a new project generated by `mix new`), it appears that perhaps your local rebar is the problem, or potentially you have an older version of `exprotobuf` in your `mix.lock`?

To get an updated rebar:

- `rm ~/.mix/rebar`
- `mix do clean, compile` (in project dir of course)
- Mix will prompt you to install rebar, do so

If you have an older `mix.lock`, you can make sure you are running the latest `exprotobuf` by running `mix deps.update exprotobuf`.

Could you give one or both of those a try and test again?

**Comment by saratchandra92** [comment]
I have tried this on another computer and I am getting the same problem. I forgot to mention that, I am getting this error when I run `iex -S mix`
Is the version that I am running correct?

**Comment by bitwalker** [comment]
@saratchandra92 Did you try the two steps I described above? If so and you are still having problems, could you post your `mix.lock` and tell me what OS you are running on? 0.11 is the latest exprotobuf, so the version appears to be correct, but I can only confirm that if I can see your `mix.lock`.

**Comment by saratchandra92** [comment]
@bitwalker I tried the steps you gave me, but there's no difference. Here is my mix.lock file.
```
%{"exprotobuf": {:hex, :exprotobuf, "0.11.0"},
  "gpb": {:hex, :gpb, "3.18.8"}}

```
I am running Linux Mint 17.2

**Comment by bitwalker** [comment]
@saratchandra92 What happens when you run `mix deps.compile gpb`?

**Comment by saratchandra92** [comment]
@bitwalker I get the same error.
```
Compiling src/gpb_scan.xrl failed:
ERROR: compile failed while processing /home/d3vil/projects/protobuf_elixir/deps/gpb: rebar_abort
** (Mix) Could not compile dependency :gpb, "/home/d3vil/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile gpb", update it with "mix deps.update gpb" or clean it with "mix deps.clean gpb"
```

**Comment by bitwalker** [comment]
@saratchandra92 Could you paste the output of `~/.mix/rebar --version` for me?

**Comment by saratchandra92** [comment]
Sure. Here is it.
```
rebar 2.3.1 R14B04 20140521_211707 git 2.3.1
```

**Comment by bitwalker** [comment]
@saratchandra92 I'm running the exact same version of everything, our only difference is OS. Could you try the following:

- `git clone https://github.com/tomas-abrahamsson/gpb`
- `cd gpb && ~/.mix/rebar compile`

Hopefully we can get a more useful compilation error there.

**Comment by saratchandra92** [comment]
@bitwalker I get the same error.
```
Compiling src/gpb_scan.xrl failed:
ERROR: compile failed while processing /home/d3vil/projects/protobuf_elixir/deps/gpb: rebar_abort
** (Mix) Could not compile dependency :gpb, "/home/d3vil/.mix/rebar" command failed. You can recompile this dependency with "mix deps.compile gpb", update it with "mix deps.update gpb" or clean it with "mix deps.clean gpb"
```

**Comment by saratchandra92** [comment]
@bitwalker I get the same error.
```
==> gpb (compile)
Compiling src/gpb_scan.xrl failed:
ERROR: compile failed while processing /home/sarat/gpb: rebar_abort
```

**Comment by bitwalker** [comment]
@saratchandra92 Could you try running `make` in that directory instead of `~/.mix/rebar compile`? I have no idea why it won't build on your machine, but I'm beginning to suspect something is wrong in your environment.

**Comment by saratchandra92** [comment]
@bitwalker I have tried this on a different Ubuntu box and the samething happens. Maybe there is aproblem with Ubuntu.

By running `make` I get the following error.
```
mkdir -pv ebin
mkdir: created directory ‘ebin’
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_codegen.erl
erlc -Wall +debug_info -Iinclude -pa ebin -o ebin src/gpb_compile.erl
src/gpb_compile.erl: undefined parse transform 'eunit_autoexport'
make: *** [ebin/gpb_compile.beam] Error 1
```

**Comment by bitwalker** [comment]
@saratchandra92 I know what the problem is, you are missing some Erlang packages. Run `sudo apt-get install erlang-eunit`, and that error will go away.

**Comment by vans163** [comment]
erlang-parsetools is also a dependent package, I had the same error until I installed that.  The depends should be listed on the README.md

**Comment by saratchandra92** [comment]
@vans163 This solved the issue for me. Thanks!!
