### ISSUE TITLE
Missing tag for version 0.11.0

### ISSUE THREAD

**Issue by olgeni** [bitwalker/exprotobuf#27]
Hi,

Can you tag version 0.11.0? It is on Hex, but there is no git tag :)

**Comment by bitwalker** [comment]
I can definitely do that, give me a few :)

**Comment by bitwalker** [comment]
Actually it turns out there is a tag for it! At least in a clone of the repo it shows up alongside commit 6f5f4bb.

**Comment by olgeni** [comment]
It's true, I didn't see the other tags. Now I have 0.12.0. Thanks! :+1:
