### ISSUE TITLE
ParseError when reading proto file

### ISSUE THREAD

**Issue by ajrob27** [bitwalker/exprotobuf#28]
When compiling my mix project I get the following error: 
```
== Compilation error on file lib/csgo_parse.ex ==
** (Protobuf.Parser.ParserError) 6('syntax error before: ', '\'.\'')
    lib/exprotobuf/parser.ex:46: Protobuf.Parser.parse!/2
    lib/exprotobuf.ex:67: Protobuf.parse/2
    expanding macro: Protobuf.__using__/1
    lib/csgo_parse.ex:2: CsgoParse (module)
    (elixir) expanding macro: Kernel.use/2
    lib/csgo_parse.ex:2: CsgoParse (module)
```

I’m importing .proto files, I’m not sure what’s wrong and/or where to go next to continue debugging it. 

My repo lives here, https://github.com/ajrob27/csgo_parse. I've created another branch where I remove most everything from the .proto file I am trying to read, https://github.com/ajrob27/csgo_parse/tree/bugfix/protobuf. 

In the `bugfix/protobuf` branch, the project still does not compile, but if you removed lines 4-6 in `steammessages.proto`, the project does compile. Is there something wrong with my .proto files? Other project successfully use these .proto files, I'm not sure where I am going wrong. 

Thanks!

**Comment by bitwalker** [comment]
The problem is that [tomas-abrahamsson/gpb](https://github.com/tomas-abrahamsson/gpb) doesn't yet support `proto2` syntax, namely extensions. I'm waiting for it to be merged there before it can be supported in `exprotobuf`. Sorry for the delay :(

**Comment by ajrob27** [comment]
Oh awesome! Thanks Paul, I'm glad it's not a bigger issue than that.
