### ISSUE TITLE
Protobuf.Encoder not available on production

### ISSUE THREAD

**Issue by rafal-radziszewski** [bitwalker/exprotobuf#32]
We included exprotobuf in our production application. After deploying release to staging, encoding does not work in staging environment. We get following error:

```** (UndefinedFunctionError) undefined function: Protobuf.Encoder.encode/2 (module Protobuf.Encoder is not available)```

Exprotobuf has been added as an application in mix. Currently we inverstigate the issue.

**Comment by rafal-radziszewski** [comment]
We tracked down the issue to the following to reasons:

1. Error above was a result of not having exprotobuf in the apps. Our builds were not correctly started, so we thought that it is already added. It was not on the working version.
2. Gpb needs to be added to exprotobuf applications. It will be extremely small merge request.

**Comment by bitwalker** [comment]
Closed via #34

**Comment by bitwalker** [comment]
Also released in 0.13.0
