### ISSUE TITLE
Can not encode certain data structures

### ISSUE THREAD

**Issue by chilicat** [bitwalker/exprotobuf#38]
Please merge request, it provides a test case.
https://github.com/bitwalker/exprotobuf/pull/37

**Comment by mmmries** [comment]
@chilicat feel free to post some details about your decoding problems here. I'm not sure if I'll be able to help, but I don't mind giving it a shot.

**Comment by bitwalker** [comment]
@chilicat You closed #37, is this issue closable as well?
