### ISSUE TITLE
Cannot compile exprotobuff as dependency for Elixir 1.2 on Win10

### ISSUE THREAD

**Issue by Inkp** [bitwalker/exprotobuf#39]
When trying to compile project I get the following output:
```
G:\projects\elixir\test>mix compile
==> gpb (compile)
Compiled src/gpb_scan.xrl
Compiled src/gpb_parse.yrl
Compiled src/gpb_scan.erl
Compiled src/gpb_parse.erl
Compiled src/gpb_codegen.erl
Compiled src/gpb.erl
Compiled src/gpb_compile.erl
'sh' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency :gpb, "escript.exe "c:/Users/Денис/.mix/rebar" compile skip_deps=true deps_dir="g:/projects/elixir/test/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile gpb", update it with "mix deps.update gpb" or clean it with "mix deps.clean gpb"
```

mix.exs file contents:
```
defmodule Test.Mixfile do
  use Mix.Project

  def project do
    [app: :test,
     version: "0.0.1",
     elixir: "~> 1.2",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
        {:exprotobuf, "~> 1.0.0-rc1"}
    ]
  end
end
```

mix.lock contents:
```
%{"exprotobuf": {:hex, :exprotobuf, "1.0.0-rc1"},
  "gpb": {:hex, :gpb, "3.18.10"}}
```

rebar --version
```
rebar 2.3.1 R14B04 20140521_211707 git 2.3.1
```

**Comment by mmmries** [comment]
It looks to me like this is probably due the fact that [gpb's Makefile](https://github.com/tomas-abrahamsson/gpb/blob/8495d7b3c2562988b80b326dc93343a946e715d6/Makefile#L45) references `/bin/sh` and tries to use that to execute some commands.

I don't know for sure how much support `gpb` has for windows overall.

**Comment by Inkp** [comment]
Cloning `gpb` and running `"C:\Program Files\erl7.2.1\bin\escript.exe" "c:/Users/Денис/.mix/rebar" compile` inside seems to finish successfully. Are you sure it is OS specific problem? And is there any workaround for this?

**Comment by mmmries** [comment]
Unfortunately I have very little rebar or windows experience. I'm not sure what the difference is between how mix calls `rebar` vs how it runs when you call it directly.

**Comment by Inkp** [comment]
For no apparent reason it now works. The only real thing I did was reinstalling erlang and elixir

**Comment by Dimagog** [comment]
Compiling from cmd.exe shell does not work, but compiling from bash shell (e.g. the one installed by Git) works fine.
