### ISSUE TITLE
Proto 3 support ?

### ISSUE THREAD

**Issue by Linicks** [bitwalker/exprotobuf#49]
Are there plans to support Proto 3 any time in the near future ?

Thanks!
--Nick

**Comment by bitwalker** [comment]
I've just pushed an update to the latest version of `gpb`, which is what exprotobuf uses for parsing ProtoBuf definitions. There is proto3 support available in that version. I haven't been able to do testing on what features work out of the box, and which things I need to extend exprotobuf to handle properly. Give 1.2 a shot and let me know if there are things missing and I'll look into it.

**Comment by Linicks** [comment]
@bitwalker, Fantastic!  I give the updated version a try;
