### ISSUE TITLE
Proto3 support

### ISSUE THREAD

**Issue by sotte** [bitwalker/exprotobuf#55]
Hey, I think `exprotobuf` does not support proto3, but I might be wrong. In any case, noting the supported version that in the README would be great!

Thanks!

PS: I guess I should mention that I'd like proto 3 support :)

**Comment by bitwalker** [comment]
It does indeed, via `gpb` the underlying protobuf parser :)

**Comment by sotte** [comment]
Great! I think this should be mentioned in the README.
