### ISSUE TITLE
Missing optional values not decoded correctly

### ISSUE THREAD

**Issue by mweberUKL** [bitwalker/exprotobuf#63]
When creating instances of messages, the optional values are correctly set to `nil`. But when decoding messages with optional values, the resulting struct-instance has the optional values to type-defaults, instead.

in `lib`:
```elixir
defmodule Exprotobufbug do
  use Protobuf, """
    message Msg {
      optional bytes timestamp = 1;
    }
  """
end
```

in `test`:
```elixir
defmodule ExprotobufbugTest do
  use ExUnit.Case
  doctest Exprotobufbug

  test "decode optional values as nil" do
    msg = Exprotobufbug.Msg.new()
    bin = Exprotobufbug.Msg.encode(msg)
    res = Exprotobufbug.Msg.decode(bin)
    assert ^res = msg
  end
end
```

result of executing the test:
```
  1) test decode optional values as nil (ExprotobufbugTest)
     test/exprotobufbug_test.exs:5
     match (=) failed
     The following variables were pinned:
       res = %Exprotobufbug.Msg{timestamp: ""}
     code:  ^res = msg
     right: %Exprotobufbug.Msg{timestamp: nil}
     stacktrace:
       test/exprotobufbug_test.exs:9: (test)
 
 
 
Finished in 0.02 seconds
1 test, 1 failure
```

As expected, the timestamp was set to `nil` by the constructor. But decoding the binary-version gives a default value for the type `binary` instead.

OS: MacOS Sierra 10.12.3
Mix: 1.4.2
Elixir: 1.4.2
Erlang: 19
exprotobuf: 1.2.5

**Comment by bitwalker** [comment]
Fixed in master, soon to be released on hex
